services:
  mysql:
    image: mysql:8.4
    container_name: svea-bilar-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: SveaBilarLocalDb
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3307:3306"

    volumes:
      - svea_bilar_mysql_data:/var/lib/mysql

volumes:
  svea_bilar_mysql_data: