spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true