spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  resend: 
    api-key: ${RESEND_API_KEY}
    
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  mail:
    from: ${MAIL_FROM}
    reply-to: ${MAIL_REPLY_TO:${MAIL_FROM}}
